# Generated by Django 4.2.16 on 2024-12-11 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_createcall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createcall',
            old_name='MeetingTime',
            new_name='meetingtime',
        ),
        migrations.RenameField(
            model_name='createcall',
            old_name='Message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='createcall',
            old_name='Receiver',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='createcall',
            old_name='Sender',
            new_name='sender',
        ),
        migrations.RemoveField(
            model_name='pointrecord',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='pointrecord',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='pointrecord',
            name='date',
        ),
        migrations.RemoveField(
            model_name='pointrecord',
            name='details',
        ),
        migrations.RemoveField(
            model_name='pointrecord',
            name='status',
        ),
    ]
