# Generated by Django 4.2.16 on 2024-12-11 07:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_meetingtime_createcall_meetingtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointrecord',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pointrecord',
            name='details',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='pointrecord',
            name='last_subscription_amount',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pointrecord',
            name='left_call',
            field=models.CharField(default='5', max_length=20),
        ),
        migrations.AddField(
            model_name='pointrecord',
            name='type_subscription',
            field=models.CharField(choices=[('free', 'free'), ('monthly', 'monthly'), ('yearly', 'yearly')], default='None', max_length=255),
        ),
    ]
